### ISSUE TITLE
non rectangular integral

### ISSUE THREAD

**Issue by hesampour** [stevengj/HCubature.jl#16]
how we can compute a non rectangular integral (which some boundaries of the integral is a variable not a static value) with this package:
something like this:
![image](https://user-images.githubusercontent.com/20963159/52712621-695a9280-2faa-11e9-99dc-a691875c0a06.png)

**Comment by MasonProtter** [comment]
I believe that needs to be done with nested one-dimensional integrals.

**Comment by hesampour** [comment]
I compute the integral in this way:
hcubature(f2,[0,t], [t1 -> t1 ,t],norm=norm, rtol=sqrt(eps), atol=0, maxevals=100, initdiv=1)

**Comment by hesampour** [comment]
@MasonProtter would you please explain more?

**Comment by MasonProtter** [comment]
Suppose I want to compute the integral:
<img width="306" alt="image" src="https://user-images.githubusercontent.com/29157027/52975319-4c470a80-3382-11e9-85fd-90a295a4c168.png">

I can't express this as a simple integral over some square domain (unless there is some clever change or basis allowed by `F`). Instead, one has to treat it as two nested integrals, ie:
```
hquadrature(u -> hquadrature(v -> F(u, v), u, t), 0, t)
```

**Comment by stevengj** [comment]
Don’t use nested 1d adaptive integrals. That is almost always suboptimal because the inner adaptation doesn’t know about the outer integral. 

You can use HCubature via a change of variables. In your example above, just change variables in the inner integral from u to `u=z*(t-v)+v` where z goes from 0 to 1, with a Jacobian factor of `t-v` multiplying the integrand.
